services:
  node:
    image: "node:17-alpine"
    user: "node"
    working_dir: /home/node/app
    expose:
      - 8080
    env_file:
      - .env
    environment:
      - NODE_ENV=developement
    volumes:
      - ./:/home/node/app
    expose:volumes:
      - "8081"
    command: "npm start"