services:
  cervus-min:
    image: "node:17-alpine"
    user: "node"
    working_dir: /home/cervus-min/app
    ports:
      - "8080:8080"
    env_file:
      - app/.env
    environment:
      - NODE_ENV=developement
    volumes:
      - ./:/home/cervus-min
    command: "npm run start"